# Lab 1  
All copy rigths to Mani Bayani, Pd.D.

# Introductionto NUMPY

In [1]:
import numpy as np 


Creating a list and converting it into numpy array.

In [2]:
listt = [2,3,5,9,8,7]
l = np.array(listt)
l

array([2, 3, 5, 9, 8, 7])

In [3]:
t = np.array([2,3,5,9,8,7,9,45])
t

array([ 2,  3,  5,  9,  8,  7,  9, 45])

To create Multi-dimensional Array pass a lists of list.

In [4]:
q = np.array([[2,3,5,9,8,7,9,45],[2,4,5,3,4,6,4,6]])
q.shape

(2, 8)

`arange` is used to return evenly spaced values within a given interval.

In [5]:
p = np.arange(0,50,5)
p

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

`linspace` is used to return evenly spaced numbers over a specified interval.

In [6]:
p = np.linspace(0,3,15)
p

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

`ones` is used to return a new array of given shape and type, filled with ones.

In [7]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`zeros` is used to return a new array of given shape and type, filled with zeros.

In [8]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

`eye` is used to return identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`diag` extracts a diagonal or constructs a diagonal array.

In [10]:
q = [1,2,3]
np.diag(q)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Combining Arrays

In [11]:
p = np.ones([2, 4], int)
p

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

Use `vstack` to stack arrays in sequence horizontally (column wise).

In [12]:
#np.vstack([p, 2*p])
np.concatenate((p,2*p),axis=1)
np.concatenate((p,2*p),axis=0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [13]:
np.exp(p)


array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [14]:
np.hstack([p, 2*p])

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

## Operations

You can use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [16]:
print(x+y)

[5 7 9]


In [17]:
print(x-y)

[-3 -3 -3]


In [18]:
print(x*y)

[ 4 10 18]


In [19]:
print(x/y)

[0.25 0.4  0.5 ]


In [20]:
print(x**y)

[  1  32 729]


We can use `.dot()` function to get the dot product.

In [21]:
x.dot(y)

32

We can use `.T` function to transpose the array

In [22]:
z = np.array([x,y])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.matmul(z,x.T)

array([14, 32])

In [25]:
z@ x.T

array([14, 32])

#### Numpy has many built in math functions that can be performed on arrays.

In [26]:
x.sum()

6

In [27]:
x.max()

3

In [28]:
x.min()

1

In [29]:
x.mean()

2.0

In [30]:
x.std()

0.816496580927726

`argmax` and `argmin` are used to return the index of the maximum and minimum values in the array.

In [31]:
x.argmax()

2

In [32]:
x.argmin()

0

### Numpy Subsettings

In [33]:
b = np.array([24.523,21.265,20.054,26.459,23.245])

In [34]:
b>23

array([ True, False, False,  True,  True])

In [35]:
b[b>23]

array([24.523, 26.459, 23.245])

# Introduction to Pandas
Pandas series Data structure

In [36]:
import pandas as pd
#TA only uses for csv files

In [37]:
shop = ['bananas', 'apples', 'strawberry']
pd.Series(shop)

0       bananas
1        apples
2    strawberry
dtype: object

In [38]:
num = [1,2,3,4,5,6,7,8]
pd.Series(num)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [39]:
shop.append(None)
pd.Series(shop)

0       bananas
1        apples
2    strawberry
3          None
dtype: object

In [40]:
num.append(None)
pd.Series(num)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    NaN
dtype: float64

# The DataFrame Data Structure

In [41]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Prakhar',
                        'Item Purchased': 'IPAD',
                        'Cost': 43000})
purchase_2 = pd.Series({'Name': 'Shubham',
                        'Item Purchased': 'Monitor',
                        'Cost': 27000})
purchase_3 = pd.Series({'Name': 'Simran',
                        'Item Purchased': 'Sneakers',
                        'Cost': 15000})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased   Cost
Store 1  Prakhar           IPAD  43000
Store 1  Shubham        Monitor  27000
Store 2   Simran       Sneakers  15000

In [42]:
df.loc['Store 2']

Name                Simran
Item Purchased    Sneakers
Cost                 15000
Name: Store 2, dtype: object

In [43]:
df.loc['Store 1']

Name Item Purchased   Cost
Store 1  Prakhar           IPAD  43000
Store 1  Shubham        Monitor  27000

In [44]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [45]:
df.loc['Store 1', 'Cost']

Store 1    43000
Store 1    27000
Name: Cost, dtype: int64

`Transpose` of the table

In [46]:
df.loc['Store 1', 'Cost']

Store 1    43000
Store 1    27000
Name: Cost, dtype: int64

In [47]:
df.T

Store 1  Store 1   Store 2
Name            Prakhar  Shubham    Simran
Item Purchased     IPAD  Monitor  Sneakers
Cost              43000    27000     15000

In [48]:
df.T.loc['Cost']

Store 1    43000
Store 1    27000
Store 2    15000
Name: Cost, dtype: object

In [49]:
df.loc['Store 1']['Cost']

Store 1    43000
Store 1    27000
Name: Cost, dtype: int64

In [50]:
df.drop('Store 1')

Name Item Purchased   Cost
Store 2  Simran       Sneakers  15000

# Dataframe Indexing and Loading

In [52]:
costs = df['Cost']
costs

Store 1    43000
Store 1    27000
Store 2    15000
Name: Cost, dtype: int64

In [53]:
costs+=200
costs

Store 1    43200
Store 1    27200
Store 2    15200
Name: Cost, dtype: int64

In [54]:
df

Name Item Purchased   Cost
Store 1  Prakhar           IPAD  43200
Store 1  Shubham        Monitor  27200
Store 2   Simran       Sneakers  15200

In [55]:
df['Cost']>30000

Store 1     True
Store 1    False
Store 2    False
Name: Cost, dtype: bool

`.head()` Fnction is used to review first five elements of your dataset

In [56]:
df.head()

Name Item Purchased   Cost
Store 1  Prakhar           IPAD  43200
Store 1  Shubham        Monitor  27200
Store 2   Simran       Sneakers  15200

In [57]:
df['Cost'].count()

3